### ISSUE TITLE
Tag a new version with a LICENSE

### ISSUE THREAD

**Issue by howardjohn** [go-logex/logex#5]
It would be great if a new version was tagged since LICENSE was added so users with license checkers can use this dependency (transiently or otherwise) without going off-tag

**Comment by TerraTech** [comment]
Another reason for a tagged release that includes the added LICENSE is:
[![GoDoc](https://godoc.org/gopkg.in/logex.v1?status.svg)](https://godoc.org/gopkg.in/logex.v1)
```
Documentation not displayed due to license restrictions.

See our [license policy](https://pkg.go.dev/license-policy).
```

In the interim, you can view the documentation at:
https://pkg.go.dev/github.com/chzyer/logex

**Comment by chzyer** [comment]
It's done now, thanks.
